on: 
  push: 
    branches: 
      - main
      - master 
    paths:
      - "src/**"
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkingOut
      uses: actions/checkout@v4
    - name: installing
      run: |
        npm install
        npm test