name: First Workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Print Welcome Message
        run: echo "Welcome to my project"
        
      - name: List Repository files
        run: ls -la
