name: Build Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm run build
        working-directory: ./temp
        shell: bash
        # cmd, pwsh

      - name: Build project
        run: npm run build
        working-directory: ./temp
        shell: bash

      - name: Print environment variables
        run: printenv
        shell: bash
